# This file lists pre-requisistes for running Docker on a host, shoutout to geerlingguy
- name: repo-epel
  src: https://github.com/geerlingguy/ansible-role-repo-epel

- name: pip
  src: https://github.com/geerlingguy/ansible-role-pip

- name: docker
  src: https://github.com/geerlingguy/ansible-role-docker
