# This file lists pre-requisistes for running Docker on a host, shoutout to geerlingguy
- name: geerlingguy.repo-epel
  src: https://github.com/geerlingguy/ansible-role-repo-epel

- name: geerlingguy.pip
  src: https://github.com/geerlingguy/ansible-role-pip

- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker
