---
# This playbook will setup the Unifi Controller using Docker
- name: Open necessary ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ ports }}"

- name: Reload firewalld
  command: firewall-cmd --reload

- name: Place docker-compose file
  copy:  
    src: ../files/
    dest: /etc/ansible/unifi/
    owner: ansible
    group: ansible

- name: Docker-compose up unifi
  become: false
  docker_compose:
    project_src: /etc/ansible/unifi
    state: present
