---
- name: Add ansible group
  group:
    name: ansible
    gid: 1010
    state: present

- name: Add user ansible
  user:
    name: ansible
    comment: Ansible
    groups: ansible,docker
    uid: 1010
    state: present

- name: Add SSH key to ansible user
  authorized_key:
    user: ansible
    key: "{{ lookup('file', '~/.ssh/homelab.pub') }}"
    state: present
